name: Deployment
on:
  push:
    branches: [hexo] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm install --save bulma-stylus@0.8.0 hexo-pagination@^2.0.0 hexo-renderer-inferno@^0.1.3
        npm i
        sed -i "40i <br><\/br><img src="https:\/\/cxd-note-img.oss-cn-hangzhou.aliyuncs.com\/typora-note-img\/beian.png\"><\/img><span href="https:\/\/beian.miit.gov.cn">苏ICP备2022041101号-1<\/span>" node_modules/hexo-theme-icarus/layout/common/footer.jsx
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        GIT_NAME: caixindi
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/caixindi/caixindi.github.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:main
    - name: Deploy to Aliyun Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "./public/"
        REMOTE_HOST: "39.104.160.208"
        REMOTE_USER: caixd
        TARGET: /home/caixd/web-blog
        EXCLUDE: "/dist/, /node_modules/"
